services:
  - type: web
    name: levelupapp  # Cambia esto al nombre de tu aplicación en Render
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn levelup.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: django-insecure-z3c4h#a2mc+kjtjdjx4k4sdhx2)s7ujqo*a_*lc_cw1$6iq0tw
      - key: DEBUG
        value: False  # Asegúrate de que DEBUG esté en False en producción
      - key: ALLOWED_HOSTS
        value: levelup-app.onrender.com  # La URL de tu aplicación en Render
      - key: DATABASE_URL
        value: postgresql://admin:3mzH8ZXMPOEfTM7Bl8PmKaoLQOJGpGpa@dpg-d0clnn2dbo4c73fjgso0-a.oregon-postgres.render.com/dblevelup
      - key: CLOUDINARY_CLOUD_NAME
        value: drynm4xwd
      - key: CLOUDINARY_API_KEY
        value: 726632658177361
      - key: CLOUDINARY_API_SECRET
        value: i4OgatTI-5FSXLdEDS-PSCgUxgA

