services:
  - type: web
    name: levelup-app
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn levelup.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "levelup-app.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: dblevelup
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: dblevelup
    plan: free
    databaseName: dblevelup
    user: admin


